// Cloudflare Pages Function (엣지) — 공유 메타(OG)·정적 본문 다국어화 (voca와 동일 컨벤션)
// 크롤러는 JS를 안 돌리므로 ?lang= 에 따라 title/description/OG·트위터 메타, canonical/og:url(자기 자신), OG 이미지(og/og-image-<lang>.png),
// JSON-LD, 정적 SEO 본문(section.seo)과 푸터를 그 언어로 갈아끼운다. 튜토리얼 본체(/ · /index.html)에만 적용 —
// privacy/terms 는 content-i18n.js 가 브라우저에서 번역한다(여기서 튜토리얼 제목을 덮어쓰지 않게 경로로 거른다).
// 기본(ko) 또는 미지원 lang → 원본 HTML 그대로(한국어).
// ⚠ M 은 index.html 의 DOC_TITLE · T(metaDesc · tutName · steps · foot*) 사본이다 — 그쪽 문구를 고치면 여기도 같이 고친다.
//   s = steps [제목, 설명] · f = [footAria, footHome, footApp, footPrivacy, footTerms, footContact, footMadeBy({Y}=Y-Systems 링크), footDesc]

const BASE = 'https://voca-tutorial.broodev.com';
const APP_URL = 'https://voca.broodev.com/';
const M = {
  "en": {"t":"How to use the Flashing Vocabulary Memorizer · 10-step tutorial | VOCA_TUTORIAL","d":"Learn the flashing vocabulary memorizer in 10 interactive steps: screen navigation, CSV decks, auto play, memorized marks, random order and TTS. Try each control yourself.","l":"en_US","a":"Flashing Vocabulary Memorizer tutorial","s":[["Welcome to the Flashing Memorizer","VOCA_DECK shows a word, then its meaning, in big letters over and over — so your brain links them by visual association. This 10-step tutorial teaches every control. Press Next to begin."],["Tap to advance","One tap shows the word, another reveals the meaning, and another moves to the next word. On a PC you can also press the spacebar. Try it on the screen above."],["Going back","Made a mistake? Press the ← key, scroll the wheel up, or swipe right on mobile to step backwards. Try it above."],["Open your own CSV deck","A deck is a plain CSV file: one line per entry, \"word,meaning\". Make it in Excel, Numbers or any text editor — no row limit. In the app, load it with the 📂 Open deck button."],["Manual / Auto mode","Auto mode advances by itself at the chosen delay (default 3 s) — perfect for hands-free repetition. Turn on Auto below and watch the screen."],["Order & start number","Study forward, backward, or in random order — random is great against memorizing the sequence instead of the words. The start number jumps to any position."],["Memorized marks & range","Mark a word as memorized and it drops out of the loop. The range setting lets you review only memorized words, or everything. Try marking the current word."],["A ↔ B direction","Flip the direction to be shown the meaning first and recall the word — the reverse test is where real memory is made. Try B → A below."],["Listen with TTS","The app can read entries aloud with your browser’s speech synthesis. Voice-only mode hides the text so you can train by ear. Turn it on and tap the screen."],["Make it yours & focus","Pick your font color and background (dark navy or black keeps the text crisp), then hide the control panel to study full-screen. That’s everything — you’re ready!"]],"f":["Site information","Home","VOCA_DECK app","Privacy Policy","Terms of Use","Contact & bug reports","made by {Y}","broodev is an app portfolio of free web apps that run right in your browser with no installation. Ads may be served through Google AdSense."]},
  "ja": {"t":"点滅式単語帳の使い方 · 10ステップチュートリアル | VOCA_TUTORIAL","d":"点滅式単語帳の使い方を10ステップの対話型デモで学べます。画面操作、CSV単語帳、自動再生、暗記マーク、ランダム順、TTSまで実際に触って確認。","l":"ja_JP","a":"点滅式単語帳チュートリアル","s":[["点滅式単語帳へようこそ","VOCA_DECKは単語と意味を大きな文字で交互に表示し、イメージ連想で記憶を結び付けるツールです。この10ステップですべての操作を学べます。「次へ」で始めましょう。"],["タップで進む","1回タップすると単語、もう1回で意味、さらにもう1回で次の単語に進みます。PCではスペースキーも使えます。上の画面で試してください。"],["戻る操作","間違えたら←キー、ホイール上、モバイルでは右スワイプで前に戻れます。上の画面で試してみましょう。"],["自分のCSV単語帳を開く","単語帳は1行に「単語,意味」と書くだけのCSVファイルです。Excelやメモ帳で作成でき、行数無制限。アプリでは📂「単語帳を開く」ボタンで読み込みます。"],["手動 / 自動モード","自動モードは設定した間隔（既定3秒）で勝手に進みます。ハンズフリー反復に最適。下の「自動」をオンにして画面を見てください。"],["順序と開始番号","順方向・逆方向・ランダムから選べます。ランダムは「並び順で覚えてしまう」のを防ぐのに効果的。開始番号で好きな位置から始められます。"],["暗記マークと表示範囲","覚えた単語にマークを付けると繰り返しから外れます。表示範囲で「暗記済のみ」の復習も可能。今の単語にマークを付けてみましょう。"],["A ↔ B 方向転換","意味を先に見て単語を思い出す逆方向出題もできます。逆テストこそ記憶が定着します。下でB → Aを試してください。"],["TTSで聞く","ブラウザの音声合成で読み上げできます。音声のみモードなら文字を隠して耳で訓練できます。オンにして画面をタップしてみてください。"],["画面を整えて集中","文字色と背景（濃紺か黒が見やすい）を選び、パネルを隠せば全画面で集中できます。これで全部です — 準備完了！"]],"f":["サイト情報","ホーム","VOCA_DECK 本体アプリ","プライバシーポリシー","利用規約","お問い合わせ・不具合報告","制作: {Y}","broodevは、インストール不要でブラウザからすぐ使える無料Webアプリを作るアプリポートフォリオです。広告はGoogle AdSenseを通じて掲載される場合があります。"]},
  "zh": {"t":"闪示单词记忆使用教程 · 10步 | VOCA_TUTORIAL","d":"通过10步交互式演示学习闪示单词记忆工具的用法：画面操作、CSV单词本、自动播放、已记标记、随机顺序与TTS，边点边学。","l":"zh_CN","a":"闪示单词记忆教程","s":[["欢迎使用闪示单词记忆","VOCA_DECK以大字交替显示单词和释义，通过图像联想连接记忆。本教程共10步，覆盖全部操作。点击\"下一步\"开始。"],["点按前进","点一下显示单词，再点一下显示释义，再点一下进入下一个单词。PC上也可以按空格键。在上方屏幕试试吧。"],["后退操作","按错了？按←键、滚轮向上，或在手机上向右滑动即可后退。在上方试试。"],["打开自己的CSV单词本","单词本就是每行\"单词,释义\"的CSV文件。用Excel或记事本都能做，行数不限。在应用中用📂\"打开单词本\"按钮载入。"],["手动 / 自动模式","自动模式按设定间隔（默认3秒）自动前进，适合解放双手反复记忆。在下方打开\"自动\"并观察屏幕。"],["顺序与起始编号","可选正向、反向或随机。随机能防止\"按顺序背下来\"的假记忆。起始编号可以跳到任意位置。"],["已记标记与显示范围","给记住的单词打上标记，它就会退出循环。显示范围还能只复习已记单词。给当前单词打个标记试试。"],["A ↔ B 方向切换","也可以先看释义再回想单词——反向测试才能形成真正的记忆。在下方试试B → A。"],["用TTS听","应用可用浏览器语音合成朗读条目。仅语音模式隐藏文字，用耳朵训练。打开后点一下屏幕试试。"],["个性化与专注模式","选择文字颜色和背景（深蓝或黑色最清晰），再隐藏控制面板即可全屏专注学习。就是这些——你准备好了！"]],"f":["网站信息","首页","VOCA_DECK 正式应用","隐私政策","使用条款","联系与错误反馈","由 {Y} 制作","broodev 是一个应用作品集，制作无需安装、在浏览器中即可直接使用的免费网页应用。广告可能通过 Google AdSense 投放。"]},
  "zh-Hant": {"t":"閃示單字記憶使用教學 · 10步 | VOCA_TUTORIAL","d":"透過10步互動式示範學習閃示單字記憶工具的用法：畫面操作、CSV單字本、自動播放、已記標記、隨機順序與TTS，邊點邊學。","l":"zh_TW","a":"閃示單字記憶教學","s":[["歡迎使用閃示單字記憶","VOCA_DECK以大字交替顯示單字與釋義，透過圖像聯想連結記憶。本教學共10步，涵蓋全部操作。點「下一步」開始。"],["點按前進","點一下顯示單字，再點一下顯示釋義，再點一下進入下一個單字。PC上也可以按空白鍵。在上方螢幕試試吧。"],["後退操作","按錯了？按←鍵、滾輪向上，或在手機上向右滑動即可後退。在上方試試。"],["開啟自己的CSV單字本","單字本就是每行「單字,釋義」的CSV檔案。用Excel或記事本都能做，行數不限。在應用中用📂「開啟單字本」按鈕載入。"],["手動 / 自動模式","自動模式依設定間隔（預設3秒）自動前進，適合解放雙手反覆記憶。在下方開啟「自動」並觀察螢幕。"],["順序與起始編號","可選正向、反向或隨機。隨機能防止「按順序背下來」的假記憶。起始編號可以跳到任意位置。"],["已記標記與顯示範圍","給記住的單字打上標記，它就會退出循環。顯示範圍還能只複習已記單字。給目前單字打個標記試試。"],["A ↔ B 方向切換","也可以先看釋義再回想單字——反向測試才能形成真正的記憶。在下方試試B → A。"],["用TTS聽","應用可用瀏覽器語音合成朗讀條目。僅語音模式隱藏文字，用耳朵訓練。開啟後點一下螢幕試試。"],["個人化與專注模式","選擇文字顏色和背景（深藍或黑色最清晰），再隱藏控制面板即可全螢幕專注學習。就是這些——你準備好了！"]],"f":["網站資訊","首頁","VOCA_DECK 正式應用","隱私權政策","使用條款","聯絡與錯誤回報","由 {Y} 製作","broodev 是一個應用作品集，製作免安裝、在瀏覽器中即可直接使用的免費網頁應用。廣告可能透過 Google AdSense 刊登。"]},
  "th": {"t":"วิธีใช้แอปท่องศัพท์แบบแฟลช · บทช่วยสอน 10 ขั้น | VOCA_TUTORIAL","d":"เรียนรู้วิธีใช้แอปท่องศัพท์แบบแฟลชผ่านการสาธิตแบบโต้ตอบ 10 ขั้นตอน: การควบคุมหน้าจอ, ชุดคำศัพท์ CSV, เล่นอัตโนมัติ, เครื่องหมายจำ, สุ่มลำดับ และ TTS","l":"th_TH","a":"บทช่วยสอนแอปท่องศัพท์แบบแฟลช","s":[["ยินดีต้อนรับสู่แอปท่องศัพท์แบบแฟลช","VOCA_DECK แสดงคำและความหมายสลับกันด้วยตัวอักษรขนาดใหญ่ ให้สมองเชื่อมโยงผ่านภาพ บทช่วยสอน 10 ขั้นนี้ครอบคลุมทุกการควบคุม กด \"ถัดไป\" เพื่อเริ่ม"],["แตะเพื่อไปต่อ","แตะครั้งแรกแสดงคำ แตะอีกครั้งแสดงความหมาย แตะอีกครั้งไปคำถัดไป บน PC ใช้สเปซบาร์ได้ ลองที่หน้าจอด้านบน"],["การย้อนกลับ","พลาดไป? กดปุ่ม ← เลื่อนล้อขึ้น หรือปัดขวาบนมือถือเพื่อถอยหลัง ลองดูด้านบน"],["เปิดชุดคำศัพท์ CSV ของคุณ","ชุดคำศัพท์คือไฟล์ CSV ธรรมดา บรรทัดละ \"คำ,ความหมาย\" สร้างได้ใน Excel หรือโปรแกรมแก้ไขข้อความใดๆ ไม่จำกัดแถว ในแอปให้โหลดด้วยปุ่ม 📂 เปิดชุดคำศัพท์"],["โหมดมือ / อัตโนมัติ","โหมดอัตโนมัติเลื่อนเองตามหน่วงเวลา (ค่าเริ่มต้น 3 วิ) เหมาะกับการทวนแบบไม่ต้องใช้มือ เปิด \"อัตโนมัติ\" ด้านล่างแล้วดูหน้าจอ"],["ลำดับและหมายเลขเริ่มต้น","เลือกไปข้างหน้า ย้อนกลับ หรือสุ่มได้ การสุ่มช่วยกันการจำ \"ตามลำดับ\" แทนที่จะจำคำ หมายเลขเริ่มต้นใช้กระโดดไปตำแหน่งใดก็ได้"],["เครื่องหมายจำและขอบเขต","ทำเครื่องหมายคำที่จำได้แล้ว มันจะออกจากรอบวน ขอบเขตยังให้ทวนเฉพาะคำที่จำได้ ลองทำเครื่องหมายคำปัจจุบันดู"],["สลับทิศ A ↔ B","สลับให้เห็นความหมายก่อนแล้วนึกคำ — การทดสอบย้อนกลับคือจุดที่ความจำจริงเกิดขึ้น ลอง B → A ด้านล่าง"],["ฟังด้วย TTS","แอปอ่านออกเสียงด้วยเสียงสังเคราะห์ของเบราว์เซอร์ได้ โหมดเสียงเท่านั้นซ่อนตัวอักษรให้ฝึกด้วยหู เปิดแล้วแตะหน้าจอดู"],["ปรับแต่งและโฟกัส","เลือกสีตัวอักษรและพื้นหลัง (น้ำเงินเข้มหรือดำคมชัดสุด) แล้วซ่อนแผงควบคุมเพื่อเรียนแบบเต็มจอ ครบแล้ว — พร้อมลุย!"]],"f":["ข้อมูลเว็บไซต์","หน้าแรก","แอป VOCA_DECK","นโยบายความเป็นส่วนตัว","ข้อกำหนดการใช้งาน","ติดต่อและแจ้งข้อผิดพลาด","สร้างโดย {Y}","broodev คือพอร์ตโฟลิโอของเว็บแอปฟรีที่ใช้งานได้ทันทีในเบราว์เซอร์โดยไม่ต้องติดตั้ง โฆษณาอาจแสดงผ่าน Google AdSense"]},
  "es": {"t":"Cómo usar el memorizador de vocabulario · Tutorial en 10 pasos | VOCA_TUTORIAL","d":"Aprende el memorizador de vocabulario en 10 pasos interactivos: navegación, mazos CSV, reproducción automática, marcas, orden aleatorio y TTS. Pruébalo tú mismo.","l":"es_ES","a":"Tutorial del memorizador de vocabulario","s":[["Bienvenido al memorizador flash","VOCA_DECK muestra una palabra y luego su significado en letras grandes, una y otra vez, para que tu cerebro los asocie visualmente. Este tutorial de 10 pasos cubre todos los controles. Pulsa Siguiente."],["Toca para avanzar","Un toque muestra la palabra, otro revela el significado y otro pasa a la siguiente. En PC también sirve la barra espaciadora. Pruébalo en la pantalla de arriba."],["Retroceder","¿Te pasaste? Pulsa la tecla ←, rueda del ratón hacia arriba, o desliza a la derecha en el móvil. Pruébalo arriba."],["Abre tu propio mazo CSV","Un mazo es un simple archivo CSV: una línea por entrada, \"palabra,significado\". Créalo en Excel o cualquier editor, sin límite de filas. En la app se carga con el botón 📂 Abrir mazo."],["Modo manual / automático","El modo auto avanza solo según el intervalo (3 s por defecto), ideal para repetir sin manos. Activa Auto abajo y observa la pantalla."],["Orden y número inicial","Estudia hacia delante, hacia atrás o en orden aleatorio: lo aleatorio evita memorizar la secuencia en vez de las palabras. El número inicial salta a cualquier posición."],["Marcas y rango","Marca una palabra como memorizada y saldrá del ciclo. El rango permite repasar solo las memorizadas, o todas. Prueba a marcar la palabra actual."],["Dirección A ↔ B","Invierte la dirección para ver primero el significado y recordar la palabra: la prueba inversa es donde se fija la memoria. Prueba B → A abajo."],["Escucha con TTS","La app puede leer en voz alta con la síntesis de voz del navegador. El modo solo voz oculta el texto para entrenar de oído. Actívalo y toca la pantalla."],["Personaliza y concéntrate","Elige color de letra y fondo (azul marino oscuro o negro se ve más nítido) y oculta el panel para estudiar a pantalla completa. Eso es todo: ¡listo!"]],"f":["Información del sitio","Inicio","App VOCA_DECK","Política de privacidad","Términos de uso","Contacto e informes de errores","creado por {Y}","broodev es un portafolio de aplicaciones web gratuitas que funcionan directamente en el navegador, sin instalación. Es posible que se muestren anuncios a través de Google AdSense."]},
  "fr": {"t":"Guide de la mémorisation de vocabulaire · Tutoriel en 10 étapes | VOCA_TUTORIAL","d":"Apprenez la mémorisation de vocabulaire en 10 étapes interactives : navigation, paquets CSV, lecture auto, marques, ordre aléatoire et TTS. Essayez chaque commande.","l":"fr_FR","a":"Tutoriel de mémorisation de vocabulaire","s":[["Bienvenue dans la mémorisation flash","VOCA_DECK affiche un mot puis son sens en grands caractères, encore et encore, pour que votre cerveau les associe visuellement. Ce tutoriel en 10 étapes couvre toutes les commandes. Appuyez sur Suivant."],["Touchez pour avancer","Un appui montre le mot, un autre révèle le sens, un autre passe au mot suivant. Sur PC, la barre d’espace fonctionne aussi. Essayez sur l’écran ci-dessus."],["Revenir en arrière","Une erreur ? Touche ←, molette vers le haut, ou glissement à droite sur mobile pour reculer. Essayez ci-dessus."],["Ouvrez votre paquet CSV","Un paquet est un simple fichier CSV : une ligne par entrée, « mot,sens ». Créez-le dans Excel ou tout éditeur, sans limite de lignes. Dans l’app, chargez-le avec le bouton 📂 Ouvrir un paquet."],["Mode manuel / auto","Le mode auto avance seul selon l’intervalle (3 s par défaut), parfait pour répéter mains libres. Activez Auto ci-dessous et regardez l’écran."],["Ordre et numéro de départ","Étudiez en avant, en arrière ou au hasard — l’aléatoire évite de mémoriser la séquence au lieu des mots. Le numéro de départ saute à n’importe quelle position."],["Marques et plage","Marquez un mot comme mémorisé et il sort de la boucle. La plage permet de revoir uniquement les mémorisés, ou tout. Essayez de marquer le mot actuel."],["Direction A ↔ B","Inversez pour voir d’abord le sens et retrouver le mot : le test inverse est là où la mémoire se fixe. Essayez B → A ci-dessous."],["Écoutez avec TTS","L’app peut lire à voix haute grâce à la synthèse vocale du navigateur. Le mode voix seule masque le texte pour entraîner l’oreille. Activez-le et touchez l’écran."],["Personnalisez et concentrez-vous","Choisissez couleur et fond (bleu marine foncé ou noir pour un texte net), puis masquez le panneau pour étudier en plein écran. C’est tout — vous êtes prêt !"]],"f":["Informations sur le site","Accueil","Application VOCA_DECK","Politique de confidentialité","Conditions d’utilisation","Contact et signalement de bugs","créé par {Y}","broodev est un portfolio d’applications web gratuites qui fonctionnent directement dans le navigateur, sans installation. Des publicités peuvent être diffusées via Google AdSense."]},
  "de": {"t":"Vokabeltrainer-Anleitung · 10-Schritte-Tutorial | VOCA_TUTORIAL","d":"Lerne den Vokabeltrainer in 10 interaktiven Schritten: Bedienung, CSV-Decks, Autoplay, Markierungen, Zufallsreihenfolge und TTS. Probiere jede Funktion selbst aus.","l":"de_DE","a":"Vokabeltrainer-Tutorial","s":[["Willkommen beim Blitz-Vokabeltrainer","VOCA_DECK zeigt Wort und Bedeutung abwechselnd in großer Schrift — dein Gehirn verknüpft sie über visuelle Assoziation. Dieses 10-Schritte-Tutorial erklärt alle Funktionen. Drücke Weiter."],["Tippen zum Fortfahren","Ein Tipp zeigt das Wort, ein weiterer die Bedeutung, der nächste springt zum nächsten Wort. Am PC geht auch die Leertaste. Probier es oben aus."],["Zurückgehen","Verklickt? Drücke ←, scrolle nach oben oder wische auf dem Handy nach rechts, um zurückzugehen. Probier es oben."],["Eigenes CSV-Deck öffnen","Ein Deck ist eine einfache CSV-Datei: eine Zeile pro Eintrag, \"Wort,Bedeutung\". Erstellbar in Excel oder jedem Editor, ohne Zeilenlimit. In der App lädst du es mit 📂 Deck öffnen."],["Manuell / Auto-Modus","Der Auto-Modus läuft von selbst im gewählten Intervall (Standard 3 s) — ideal fürs freihändige Wiederholen. Schalte unten Auto ein und beobachte den Bildschirm."],["Reihenfolge & Startnummer","Lerne vorwärts, rückwärts oder zufällig — Zufall verhindert, dass du die Reihenfolge statt der Wörter lernst. Die Startnummer springt an jede Position."],["Markierungen & Bereich","Markiere ein Wort als gemerkt und es fällt aus der Schleife. Über den Bereich kannst du auch nur Gemerktes wiederholen. Markiere das aktuelle Wort."],["Richtung A ↔ B","Dreh die Richtung um: erst die Bedeutung sehen, das Wort erinnern — im Rückwärtstest entsteht echtes Gedächtnis. Probiere unten B → A."],["Mit TTS hören","Die App liest Einträge per Browser-Sprachsynthese vor. Der Nur-Ton-Modus versteckt den Text zum Hörtraining. Einschalten und auf den Bildschirm tippen."],["Anpassen & fokussieren","Wähle Schriftfarbe und Hintergrund (dunkles Marineblau oder Schwarz ist am schärfsten) und blende das Panel aus, um im Vollbild zu lernen. Das war’s — du bist bereit!"]],"f":["Website-Informationen","Startseite","VOCA_DECK-App","Datenschutzerklärung","Nutzungsbedingungen","Kontakt & Fehlermeldungen","erstellt von {Y}","broodev ist ein Portfolio kostenloser Web-Apps, die ohne Installation direkt im Browser laufen. Werbung kann über Google AdSense ausgeliefert werden."]},
  "it": {"t":"Come usare il memorizzatore di vocaboli · Tutorial in 10 passi | VOCA_TUTORIAL","d":"Impara il memorizzatore di vocaboli in 10 passi interattivi: navigazione, mazzi CSV, riproduzione automatica, contrassegni, ordine casuale e TTS. Prova ogni comando.","l":"it_IT","a":"Tutorial del memorizzatore di vocaboli","s":[["Benvenuto nel memorizzatore flash","VOCA_DECK mostra una parola e poi il suo significato a caratteri grandi, più volte, così il cervello li collega per associazione visiva. Questo tutorial in 10 passi copre tutti i comandi. Premi Avanti."],["Tocca per avanzare","Un tocco mostra la parola, un altro rivela il significato, un altro passa alla successiva. Su PC funziona anche la barra spaziatrice. Provalo sullo schermo qui sopra."],["Tornare indietro","Sbagliato? Premi ←, rotella verso l’alto, o scorri a destra su mobile per tornare indietro. Prova qui sopra."],["Apri il tuo mazzo CSV","Un mazzo è un semplice file CSV: una riga per voce, \"parola,significato\". Crealo con Excel o qualsiasi editor, senza limiti di righe. Nell’app si carica con 📂 Apri mazzo."],["Modalità manuale / auto","La modalità auto avanza da sola secondo l’intervallo (3 s di default), perfetta per ripetere a mani libere. Attiva Auto qui sotto e osserva lo schermo."],["Ordine e numero iniziale","Studia in avanti, all’indietro o a caso — il casuale evita di memorizzare la sequenza invece delle parole. Il numero iniziale salta a qualsiasi posizione."],["Contrassegni e ambito","Contrassegna una parola come memorizzata e uscirà dal ciclo. L’ambito permette di ripassare solo le memorizzate, o tutte. Prova a contrassegnare la parola attuale."],["Direzione A ↔ B","Inverti la direzione: prima il significato, poi ricordi la parola — il test inverso è dove la memoria si fissa davvero. Prova B → A qui sotto."],["Ascolta con TTS","L’app può leggere ad alta voce con la sintesi vocale del browser. La modalità solo voce nasconde il testo per allenare l’orecchio. Attivala e tocca lo schermo."],["Personalizza e concentrati","Scegli colore del testo e sfondo (blu scuro o nero è più nitido), poi nascondi il pannello per studiare a schermo intero. È tutto: sei pronto!"]],"f":["Informazioni sul sito","Inizio","App VOCA_DECK","Informativa sulla privacy","Termini di utilizzo","Contatti e segnalazione bug","creato da {Y}","broodev è un portfolio di app web gratuite che funzionano direttamente nel browser, senza installazione. Gli annunci possono essere pubblicati tramite Google AdSense."]},
  "pt": {"t":"Como usar o memorizador de vocabulário · Tutorial em 10 passos | VOCA_TUTORIAL","d":"Aprende o memorizador de vocabulário em 10 passos interativos: navegação, baralhos CSV, reprodução automática, marcas, ordem aleatória e TTS. Experimenta cada comando.","l":"pt_PT","a":"Tutorial do memorizador de vocabulário","s":[["Bem-vindo ao memorizador flash","O VOCA_DECK mostra uma palavra e depois o significado em letras grandes, repetidamente, para o cérebro os ligar por associação visual. Este tutorial de 10 passos cobre todos os comandos. Carrega em Seguinte."],["Toca para avançar","Um toque mostra a palavra, outro revela o significado e outro passa à seguinte. No PC também funciona a barra de espaço. Experimenta no ecrã acima."],["Recuar","Enganaste-te? Prime ←, roda a roda para cima, ou desliza para a direita no telemóvel. Experimenta acima."],["Abre o teu baralho CSV","Um baralho é um simples ficheiro CSV: uma linha por entrada, \"palavra,significado\". Cria-o no Excel ou em qualquer editor, sem limite de linhas. Na app carrega-se com 📂 Abrir baralho."],["Modo manual / auto","O modo auto avança sozinho no intervalo escolhido (3 s por defeito) — perfeito para repetir sem mãos. Ativa Auto em baixo e observa o ecrã."],["Ordem e número inicial","Estuda para a frente, para trás ou aleatoriamente — o aleatório evita memorizar a sequência em vez das palavras. O número inicial salta para qualquer posição."],["Marcas e âmbito","Marca uma palavra como memorizada e ela sai do ciclo. O âmbito permite rever só as memorizadas, ou todas. Experimenta marcar a palavra atual."],["Direção A ↔ B","Inverte a direção: vê primeiro o significado e recorda a palavra — o teste inverso é onde a memória se fixa. Experimenta B → A em baixo."],["Ouvir com TTS","A app pode ler em voz alta com a síntese de voz do navegador. O modo só voz esconde o texto para treinar de ouvido. Ativa-o e toca no ecrã."],["Personaliza e concentra-te","Escolhe a cor do texto e o fundo (azul-escuro ou preto fica mais nítido) e oculta o painel para estudar em ecrã inteiro. É tudo — estás pronto!"]],"f":["Informações do site","Início","App VOCA_DECK","Política de privacidade","Termos de utilização","Contacto e relatórios de erros","criado por {Y}","O broodev é um portefólio de aplicações web gratuitas que funcionam diretamente no navegador, sem instalação. Podem ser apresentados anúncios através do Google AdSense."]},
  "ru": {"t":"Как пользоваться тренажёром слов · Обучение из 10 шагов | VOCA_TUTORIAL","d":"Освойте тренажёр слов за 10 интерактивных шагов: управление, CSV-наборы, автоповтор, отметки, случайный порядок и озвучка. Попробуйте каждую функцию сами.","l":"ru_RU","a":"Обучение работе с тренажёром слов","s":[["Добро пожаловать в флеш-тренажёр","VOCA_DECK показывает слово, затем его значение крупным шрифтом, снова и снова — мозг связывает их через зрительную ассоциацию. Эти 10 шагов охватывают всё управление. Нажмите «Далее»."],["Касание — вперёд","Одно касание показывает слово, второе — значение, третье — следующее слово. На ПК работает и пробел. Попробуйте на экране выше."],["Назад","Промахнулись? Клавиша ←, колесо вверх или свайп вправо на телефоне вернут назад. Попробуйте выше."],["Откройте свой CSV-набор","Набор — это простой CSV-файл: одна строка на запись, «слово,значение». Создаётся в Excel или любом редакторе, без лимита строк. В приложении загружается кнопкой 📂 «Открыть набор»."],["Ручной / автоматический режим","Авторежим листает сам с заданным интервалом (по умолчанию 3 с) — идеально для повторения без рук. Включите «Авто» ниже и смотрите на экран."],["Порядок и стартовый номер","Учите вперёд, назад или вразброс — случайный порядок не даёт запомнить последовательность вместо слов. Стартовый номер переносит в любую позицию."],["Отметки и диапазон","Отметьте слово как выученное — и оно выпадет из цикла. Диапазон позволяет повторять только выученное или всё. Отметьте текущее слово."],["Направление A ↔ B","Переверните направление: сначала значение, потом вспоминаете слово — обратный тест и создаёт настоящую память. Попробуйте B → A ниже."],["Слушайте с TTS","Приложение озвучивает записи синтезом речи браузера. Режим «только звук» скрывает текст для тренировки на слух. Включите и коснитесь экрана."],["Настройте под себя и фокус","Выберите цвет текста и фон (тёмно-синий или чёрный — самые чёткие), затем скройте панель и занимайтесь на весь экран. Это всё — вы готовы!"]],"f":["Информация о сайте","Главная","Приложение VOCA_DECK","Политика конфиденциальности","Условия использования","Связь и сообщения об ошибках","разработано {Y}","broodev — портфолио бесплатных веб-приложений, которые работают прямо в браузере без установки. Реклама может показываться через Google AdSense."]},
  "nl": {"t":"Zo gebruik je de woordjestrainer · Tutorial in 10 stappen | VOCA_TUTORIAL","d":"Leer de woordjestrainer in 10 interactieve stappen: bediening, CSV-decks, autoplay, markeringen, willekeurige volgorde en TTS. Probeer elke functie zelf.","l":"nl_NL","a":"Tutorial woordjestrainer","s":[["Welkom bij de flits-woordjestrainer","VOCA_DECK toont een woord en daarna de betekenis in grote letters, telkens opnieuw — je brein koppelt ze via visuele associatie. Deze tutorial van 10 stappen behandelt alle functies. Druk op Volgende."],["Tik om verder te gaan","Eén tik toont het woord, nog één onthult de betekenis en nog één gaat naar het volgende woord. Op de pc werkt ook de spatiebalk. Probeer het op het scherm hierboven."],["Teruggaan","Misgetikt? Druk op ←, scrol omhoog of veeg op mobiel naar rechts om terug te gaan. Probeer het hierboven."],["Open je eigen CSV-deck","Een deck is een simpel CSV-bestand: één regel per item, \"woord,betekenis\". Te maken in Excel of elke editor, zonder regellimiet. In de app laad je het met 📂 Deck openen."],["Handmatig / automatisch","De automodus gaat vanzelf verder volgens het interval (standaard 3 s) — ideaal voor handsfree herhalen. Zet Auto hieronder aan en kijk naar het scherm."],["Volgorde en startnummer","Leer vooruit, achteruit of willekeurig — willekeurig voorkomt dat je de volgorde onthoudt in plaats van de woorden. Met het startnummer spring je naar elke positie."],["Markeringen en bereik","Markeer een woord als geleerd en het valt uit de lus. Met het bereik herhaal je alleen geleerde woorden, of alles. Markeer het huidige woord eens."],["Richting A ↔ B","Draai de richting om: eerst de betekenis zien en het woord herinneren — de omgekeerde test is waar echt geheugen ontstaat. Probeer B → A hieronder."],["Luisteren met TTS","De app kan items voorlezen met de spraaksynthese van de browser. De alleen-geluid-modus verbergt de tekst om op het gehoor te trainen. Zet aan en tik op het scherm."],["Maak het eigen & focus","Kies tekstkleur en achtergrond (donker marineblauw of zwart is het scherpst) en verberg het paneel om schermvullend te studeren. Dat is alles — je bent klaar!"]],"f":["Website-informatie","Startpagina","VOCA_DECK-app","Privacybeleid","Gebruiksvoorwaarden","Contact & foutmeldingen","gemaakt door {Y}","broodev is een portfolio van gratis webapps die zonder installatie direct in je browser werken. Advertenties kunnen via Google AdSense worden weergegeven."]},
};

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const shortTitle = (m) => m.t.replace(/ \| VOCA_TUTORIAL$/, '');

function seoHtml(lang, m) {
  return '<h1>' + esc(shortTitle(m)) + '</h1>' +
    '<p>' + esc(m.d) + '</p>' +
    '<ol>' + m.s.map((x) => '<li><strong>' + esc(x[0]) + '</strong> — ' + esc(x[1]) + '</li>').join('') + '</ol>' +
    '<p><a href="' + APP_URL + '?lang=' + lang + '">VOCA_DECK →</a></p>';
}

function footHtml(lang, m) {
  const [, home, app, privacy, terms, contact, madeBy, desc] = m.f;
  const q = '?lang=' + encodeURIComponent(lang);
  const sep = '<span class="sep"> · </span>';
  const ys = '<a href="https://dev.broodev.com/"><strong>Y-Systems</strong></a> ↗';
  return '<nav class="foot-links">' +
    '<a href="/' + q + '">' + esc(home) + '</a>' + sep +
    '<a href="' + APP_URL + q + '">' + esc(app) + '</a>' + sep +
    '<a href="/privacy.html' + q + '">' + esc(privacy) + '</a>' + sep +
    '<a href="/terms.html' + q + '">' + esc(terms) + '</a>' + sep +
    '<a class="contact-link" href="https://voca.broodev.com/contact.html?app=voca-tutorial&amp;lang=' + encodeURIComponent(lang) + '">📮 ' + esc(contact) + '</a>' +
    '</nav>' +
    '<p style="margin:8px 0 0">© 2026 <strong>broodev</strong> · ' + esc(madeBy).replace('{Y}', ys) + '</p>' +
    '<p class="foot-desc">' + esc(desc) + '</p>';
}

function ldJson(m) {
  const data = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebApplication',
        name: 'VOCA_TUTORIAL — ' + m.a,
        url: BASE + '/',
        applicationCategory: 'EducationalApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
        isAccessibleForFree: true,
        inLanguage: ['ko', 'en', 'ja', 'zh', 'zh-Hant', 'th', 'es', 'fr', 'de', 'it', 'pt', 'ru', 'nl'],
        description: m.d,
      },
      { '@type': 'HowTo', name: shortTitle(m), step: m.s.map((x, i) => ({ '@type': 'HowToStep', position: i + 1, name: x[0] })) },
    ],
  };
  return JSON.stringify(data).replace(/</g, '\\u003c');
}

class AttrSetter { constructor(v, a = 'content') { this.v = v; this.a = a; } element(el) { el.setAttribute(this.a, this.v); } }
class TextSetter { constructor(v) { this.v = v; } element(el) { el.setInnerContent(this.v); } }
class HtmlSetter { constructor(v, attrs = {}) { this.v = v; this.attrs = attrs; } element(el) { for (const k in this.attrs) el.setAttribute(k, this.attrs[k]); el.setInnerContent(this.v, { html: true }); } }
class LangSetter { constructor(v) { this.v = v; } element(el) { el.setAttribute('lang', this.v); el.setAttribute('data-seo-lang', this.v); } }
// og:locale:alternate 목록에서 현재 언어(이제 og:locale)를 ko_KR 로 바꿔 13개 로캘이 한 번씩만 나오게
class LocaleAltSwap { constructor(cur) { this.cur = cur; } element(el) { if (el.getAttribute('content') === this.cur) el.setAttribute('content', 'ko_KR'); } }

export async function onRequest(context) {
  const { request, next } = context;
  const res = await next();
  try {
    const ct = res.headers.get('content-type') || '';
    if (!ct.includes('text/html')) return res;
    const url = new URL(request.url);
    if (!['/', '/index.html', '/index'].includes(url.pathname)) return res; // 튜토리얼 본체만
    const lang = url.searchParams.get('lang');
    const m = lang && M[lang];
    if (!m) return res; // ko/미지정/미지원 → 원본(한국어) 그대로

    const self = BASE + '/?lang=' + encodeURIComponent(lang);
    const img = BASE + '/og/og-image-' + lang + '.png';
    return new HTMLRewriter()
      .on('html', new LangSetter(lang))
      .on('title', new TextSetter(m.t))
      .on('meta[name="description"]', new AttrSetter(m.d))
      .on('link[rel="canonical"]', new AttrSetter(self, 'href'))
      .on('meta[property="og:url"]', new AttrSetter(self))
      .on('meta[property="og:title"]', new AttrSetter(m.t))
      .on('meta[property="og:description"]', new AttrSetter(m.d))
      .on('meta[property="og:locale"]', new AttrSetter(m.l))
      .on('meta[property="og:locale:alternate"]', new LocaleAltSwap(m.l))
      .on('meta[property="og:image"]', new AttrSetter(img))
      .on('meta[property="og:image:alt"]', new AttrSetter(m.a + ' VOCA_TUTORIAL'))
      .on('meta[name="twitter:title"]', new AttrSetter(m.t))
      .on('meta[name="twitter:description"]', new AttrSetter(m.d))
      .on('meta[name="twitter:image"]', new AttrSetter(img))
      .on('script[type="application/ld+json"]', new HtmlSetter(ldJson(m)))
      .on('section.seo', new HtmlSetter(seoHtml(lang, m), { lang, 'aria-label': m.a }))
      .on('footer.site-foot', new HtmlSetter(footHtml(lang, m), { 'aria-label': m.f[0] }))
      .transform(res);
  } catch (e) {
    return res;
  }
}
